config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'friend_portfolio/:id', to: 'users#friends_portfolio', as: 'friend_portfolio'
  get 'my_friends', to: 'friendships#index'
  get 'search_stock', to: 'stocks#search_stock'
  get 'search_friend', to: 'friendships#search_friend'
  get 'friend_profile/:user', to: 'users#show', as: 'friend_profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :ticker, presence: true, uniqueness: true
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.new_lookup(symbol)
    begin
      StockQuote::Stock.new(api_key: Rails.application.credentials.iex_cloud[:access_key])
      stock = StockQuote::Stock.quote symbol
      new(ticker: symbol, name: stock.company_name, last_price: stock.iex_realtime_price)
    rescue => exception
      nil
    end
  end

  def self.check_db(ticker)
    where(ticker: ticker).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock

    stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker)
    under_stock_limit? && !(stock_already_tracked? ticker)
  end

  def can_add_friend?(user_id)
    !friends.where(id: user_id).exists?
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name && last_name
    "Anonymous" 
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :user_friends

  def index
  end

  def search_friend
    @users = User.where('first_name like ? ', "%#{params[:input]}%").or(User.where('last_name like ? ', "%#{params[:input]}%")).or(User.where('email like ? ', "%#{params[:input]}%")).and(User.where.not(id: current_user.id))
    respond_to do |format|
      format.html { render partial: 'preview_list'}
    end
  end

  def create
    respond_to do |format|
      if !current_user.friends.where(id: params[:user]).exists?
        if current_user.friendships.build(friend_id: params[:user]).save
          flash.now[:success] = 'Friend added'
        else
          flash.now[:alert] = "Can't add #{user.full_name} as friend"
        end
      else
        flash.now[:notice] = 'Already added as friend'
      end
        format.html { render partial: 'list'}
    end
  end

  def destroy
    respond_to do |format|
      if current_user.friendships.where(friend_id: params[:id]).delete_all
        flash.now[:success] = 'Friend unfollowed successfully'
      else
        flash.now[:alert] = "Can't unfollow friend"
      end
      format.html { render partial: 'list'}
    end
  end

  private
  def user_friends
    @friends = current_user.friends
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  include ActionView::RecordIdentifier
  protect_from_forgery except: :search_stock

  def search_stock
    if params[:stock].present?
      @stock = Stock.new_lookup params[:stock]
      if @stock
        respond_to do |format|
          format.html {render partial: 'stocks/details' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Please enter a valid symbol'
          format.html {render partial: 'stocks/details' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a symbol'
        format.html {render partial: 'stocks/details' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  before_action :user_stocks
  
  def create
    stock = Stock.check_db user_stock_params[:ticker] 
    stock = Stock.new_lookup(user_stock_params[:ticker]) if stock.blank?
    stock.save if stock.blank?

    respond_to do |format|
      if !current_user.stock_already_tracked?(user_stock_params[:ticker])
        UserStock.create user: current_user, stock: stock
        flash.now[:success] = 'Stock added'
      else
        flash.now[:alert] = 'Stock already tracked'
      end
      format.html { render partial: 'list', locals: { user: @user} }
    end
  end

  def destroy
    respond_to do |format|
      flash.now[:notice] = if UserStock.where(stock_id: params[:id], user_id: current_user.id).delete_all
        'Stock deleted'
      else
        'Stock can not be deleted'
      end
      format.html { render partial: 'list', locals: { user: @user} }
    end
  end

  private

  def user_stock_params
    params.permit(:user, :ticker)
  end

  def user_stocks
    if params[:user] && current_user.id != params[:user]
      @stocks = User.find(params[:user]).stocks
      @user   = params[:user]
    else
      @stocks = current_user.stocks
      @user   = current_user.id
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def destroy
      super do
        # Turbo requires redirects be :see_other (303); so override Devise default (302)
        return redirect_to after_sign_out_path_for(resource_name), status: :see_other
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  def my_portfolio
    @stocks = current_user.stocks
  end

  def friends_portfolio
    @stocks = User.find(params[:id]).stocks
    respond_to do |format|
      format.html { render partial: 'user_stocks/list', locals: { user: params[:id] } }
    end
  end

  def show
    @user = User.find(params[:user])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_list.html.erb
<%= turbo_frame_tag :my_friends_list do %>
  <div class="mt-3 results-block">
		<%= render 'layouts/messages' %>
	</div>
  <div class="row mt-3">
    <div class="col-9">
      <table class="table table-dark table-hover">
        <thead>
          <tr>
            <td>Email</td>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Actions</td>
          </tr>
        <thead>
        <tbody>
          <% if @friends %>
            <% @friends.each do |friend| %>
            <tr>
              <td><%= friend.email %></td>
              <td><%= friend.first_name %></td>
              <td><%= friend.last_name %></td>
              <td>
                <%= link_to friendship_path(friend.id), data: { turbo_frame: :user_friends, turbo_method: :delete }, class:'btn btn-sm btn-warning'  do %>
                  <%= fa_icon 'remove' %> Unfollow
                <% end %>

                <%= link_to friend_profile_path(user: friend.id), class: 'btn btn-sm btn-info' do %>
                  <%= fa_icon 'search' %> Profile
                <% end %>
              </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/friendships/_preview.html.erb
<div class='card card-header results-block mt-3'>
  <strong>Email </strong> <%=user.email%>
  <strong>Name</strong> <%=user.first_name%> <%=user.last_name%>
  <% if current_user.can_add_friend? user.id %>
    <%= link_to friendships_path(user: user.id), method: :post, data: { turbo_frame: :my_friends_list, turbo_method: :post }, class: 'btn btn-sm btn-primary' do %>
      <%= fa_icon 'plus' %> Follow
    <% end %>
  <% else %>
    <span class="badge bg-secondary badge-sm">Friends</span>
  <% end %>
  <%= link_to friend_profile_path(user: user.id), class: 'btn btn-sm btn-info' do %>
    <%= fa_icon 'search' %> Profile
  <% end %>
</div>

app/views/friendships/_preview_list.html.erb
<%= turbo_frame_tag :friend_preview do %>
  <div class="mt-3 results-block">
		<%= render 'layouts/messages' %>
	</div>
  <% @users.each do |user|%>
    <%= render 'preview', user: user %>
  <% end %>
<% end %>  

app/views/friendships/index.html.erb
<h1>My Friends</h1>

<%= form_with url: search_friend_path, 
      method: :get,
      data: { turbo_frame: :friend_preview } do |f| %>
  <div class="form-group row">
      <div class="col-sm-9 no-r-padding">
          <%= text_field_tag :input, params[:input], placeholder:"email or name", autofocus: true, class:"form-control form-control-lg", required: true%>
      </div>
      <div class="col-sm-3 no-l-padding">
          <%= button_tag class: "btn btn-success" do %>    
              <%=  fa_icon 'search 2x' %>
          <% end %>
      </div>
  </div>
<% end %>

<%= turbo_frame_tag :friend_preview do %>
<% end %>

<%= turbo_frame_tag :my_friends_list do %>
  <%= render 'list' %>
<% end %>

app/views/layouts/_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

<% if flash[:success] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= flash[:success] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<ul class="nav justify-content-center bg-dark mb-3">
    <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to 'Home', root_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'My portfolio', my_portfolio_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'My Friends', my_friends_path, class:'nav-link' %>
        </li>
        <li class="nav-item">    
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to edit_user_registration_path , class:"nav-link" do %>
                <%= fa_icon 'user' %> <%= current_user.full_name %>
            <% end %>
        </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_details.html.erb
<%= turbo_frame_tag :stock_details do %>
	<div class="mt-3 results-block">
		<%= render 'layouts/messages' %>
	</div>
	<% if @stock %>
		<div class='card card-header results-block mt-3'>
			<strong>Symbol </strong> <%=@stock.ticker%>
			<strong>Name</strong> <%=@stock.name%>
			<strong>Last Price</strong> <%=@stock.last_price%>
			<% if current_user.can_track_stock? @stock.ticker %>
				<%= link_to 'Track to My Portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), method: :post, data: { turbo_frame: :user_stocks, turbo_method: :post }  %>
			<% end %>
		</div>
	<% end %>
<% end %>

app/views/user_stocks/_list.html.erb
<%= turbo_frame_tag :user_stocks do %>
  <div class="mt-3 results-block">
    <%= render 'layouts/messages' %>
  </div>
  <% if !@stocks.empty? %>
    <div class="row mt-3">
      <div class="col-9">
        <table class="table table-dark table-hover">
          <thead>
            <tr>
              <td>Ticker</td>
              <td>Name</td>
              <td>Price</td>
              <td>Actions</td>
            </tr>
          <thead>
          <%= turbo_frame_tag :new_user_stock do %>
            <tbody>
              <% @stocks.each do |stock| %>
              <tr>
                <td><%= stock.ticker %></td>
                <td><%= stock.name %></td>
                <td><%= stock.last_price %></td>
                <td>
                  <% 
                    remove_path = user_stock_path(id: stock.id)
                    remove_path = user_stock_path(user: user, id: stock.id) if defined?user 
                    add_path = user_stocks_path(ticker: stock.ticker)
                    add_path = user_stocks_path(user: user, ticker: stock.ticker) if defined?user
                  %>
                  <% if current_user.stock_already_tracked? stock.ticker %>
                    <%= link_to  remove_path, data: {turbo_frame: :user_stocks, turbo_method: :delete, turbo_confirm: 'Are you sure you wanna remove this stock from *your* portfolio?' }, class:'btn btn-xs btn-danger' do %>
                      <%= fa_icon 'remove' %> Remove
                    <% end %>
                  <% else %>
                    <% if current_user.can_track_stock? stock.ticker %>
                      <%= link_to 'Track to My Portfolio', add_path, method: :post, data: {turbo_frame: :user_stocks, turbo_method: :post }  %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_contact.html.erb
<%= turbo_frame_tag :body do %>
  <h5 class="card-title"><%= @user.full_name %> 
    <% if !current_user.can_add_friend? @user.id %> 
      <span class="badge bg-secondary badge-sm">Friends</span>
    <% end %>
  </h5>
  <p class="card-text"><%= @user.email %></p>
  <p class="card-text">Stocks: <%= @user.stocks.count %></p>
  <p class="card-text">Friends: <%= @user.friends.count %></p>
  <% if current_user.can_add_friend? @user.id %>
    <%= link_to friendships_path(user: @user.id), method: :post, data: { turbo_frame: :my_friends_list, turbo_method: :post }, class: 'btn btn-sm btn-primary' do %>
      <%= fa_icon 'plus' %> Follow
    <% end %>
  <% end %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<div class="search-area">
    <h3>Search Stocks</h3>
		<%= form_with url: search_stock_path, 
					method: :get,
					data: { turbo_frame: :stock_details } do |f| %>
			<div class="form-group row">
					<div class="col-sm-9 no-r-padding">
							<%= text_field_tag :stock, params[:stock], placeholder:"Stock ticker symbol", autofocus: true, class:"form-control form-control-lg", required: true%>
					</div>
					<div class="col-sm-3 no-l-padding">
							<%= button_tag class: "btn btn-success" do %>    
									<%=  fa_icon 'search 2x' %>
							<% end %>
					</div>
			</div>
		<% end %>
</div>

<%= turbo_frame_tag :stock_details do %>
<% end %>


<%= turbo_frame_tag :user_stocks do %>
	<%= render 'user_stocks/list' , user: current_user.id   %>
<% end %>

app/views/users/show.html.erb
<h1>User Details</h1>

 <div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <%= link_to 'Contact', friend_profile_path(user: @user),class:'nav-link active', data:{turbo_frame: :body } %>
      </li>
      <li class="nav-item">
        <%= link_to 'Portfolio', friend_portfolio_path(@user),class:'nav-link', data:{turbo_frame: :user_stocks } %>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <%= turbo_frame_tag :body do %>
      <%= render partial: 'contact' %>
    <% end %>
    <div class="container d-flex align-items-center justify-content-center">
      <%= turbo_frame_tag :user_stocks do %>
      <% end %>
    </div>
    
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the finance tracker app</h1>

<%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}%>